#!/data/data/com.termux/files/usr/bin/bash
cyan='\033[1;36m'
 green='\033[1;32m'
  red='\033[1;31m'
   yellow='\033[1;33m'
    blue='\033[1;34m'
    purple='\033[1;35m'
     reset='\033[0m'
     grey='\033[1;30m'
     echo -e "$grey Powered By EasyShell By Suyash.... "
     echo -e "$green"
     sleep 1
